

package proyecto;

import com.sun.javafx.font.Glyph;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import sun.invoke.empty.Empty;

/**
 *
 * @author toshiba
 */
public class SeleccionJugador extends javax.swing.JFrame {

    /**
     * Creates new form RegistroJugador
     */
    ArrayList<Jugadores> ListaPersonajes = new ArrayList<Jugadores>();
    
    ArrayList<Object> jugador=new ArrayList<>();
    int cont=0;
    int victorias=0;
    
    
    ClsControlador controller =new ClsControlador();

    DefaultComboBoxModel listaJugadoresModel = 
            new DefaultComboBoxModel(jugador.toArray());
    
   String[] personajes = new String[]{"Neptuno","Fire","Lodo","Avatar"};
    DefaultComboBoxModel combopersonajes= new DefaultComboBoxModel(personajes);
    ///////////
    
    boolean activarjugador1=false;
    boolean activarjugador2=false;
    
     ////////////////////pantalla Batalla//////////////
         ArrayList ListaJugadas = new ArrayList ();
    boolean repetircancion = true; 
    
    int vida1;
    int estamina1;
    int ataque1;
    int ataquefinal1;
    int defensa1;
    int curar1;
    int vida2;
    int estamina2;
    int ataque2;
    int ataquefinal2;
    int defensa2;
    int curacion2;
    int i,j;
    boolean defensaactiva = false;
       
    
    public SeleccionJugador() {
        initComponents();
        
        cmbPersonajes.setModel(combopersonajes);
        
        jugador=controller.extraerObjetos("jugadores.dat");
     
        llenarCombo();
        llenarTabla();
     
     
     if(jugador.size() > 0){
            ClsJugador ultimo = (ClsJugador) jugador.get(jugador.size()-1);
            cont=ultimo.getId();
        }
     //para los botononbes de eliminar y editar esten desabilidatos
        //el lapiz actualiza o edita la lista
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
      
        ///////////// desabilitado de los botones de batalla////
        txtVida1.setEnabled(false);
        txtVida2.setEnabled(false);
        txtEstamina1.setEnabled(false);
        txtEstamina2.setEnabled(false);      
        btnAtaque1.setEnabled(false);
        btnAtaqueFinal1.setEnabled(false);
        btnDefenza1.setEnabled(false);
        btnCurar1.setEnabled(false);
        
         btnEmpezar.setEnabled(false);
                  
       
    }

    public void llenarCombo(){
       if(jugador.size() > 0){
            cmbJugadores.setEnabled(true);
            
            jugador = controller.extraerObjetos("jugadores.dat");
            cmbJugadores.setModel(new javax.swing.DefaultComboBoxModel(jugador.toArray()));
            cmbJugador1.setModel(new javax.swing.DefaultComboBoxModel(jugador.toArray()));
            cmbJugador2.setModel(new javax.swing.DefaultComboBoxModel(jugador.toArray()));
        }else{
            cmbJugadores.setEnabled(false);
            
        }         
    }
    
    
    
    public void llenarTabla(){
        
        String nombre=txtNombre.getText();
        String apellido=txtApellido.getText();
        String usuario=txtUsuario.getText();
        String cedula=txtCedula.getText();

       if(jugador.size() > 0){         
            ClsJugador est=new ClsJugador(cont,nombre,apellido,cedula,usuario,victorias);
            DefaultTableModel model = (DefaultTableModel) tblRegistros.getModel();
            for(int i = 0; i < jugador.size(); i ++){
                est = (ClsJugador) jugador.get(i);
                Object jugadorG [] = {est.getId(),est.getNombre(),est.getApellido(),est.getCedula(),est.getUsuario()};
                model.insertRow(i, jugadorG);
            }
        }     
       
    }
    
     public void limpiar(){
         
        txtNombre.setText(null);
        txtApellido.setText(null);
        txtCedula.setText(null);
        txtUsuario.setText(null);
        
        btnGuardar.setEnabled(true);
    }
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistroJugador = new javax.swing.JFrame();
        cmbJugadores = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistros = new javax.swing.JTable();
        btnSeleccionPersonaje = new javax.swing.JButton();
        lblFondo1 = new javax.swing.JLabel();
        PantallaBatalla = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        panelFondo = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblNombreJugador1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtVida1 = new javax.swing.JTextField();
        txtEstamina1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        lblNombreJugador2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtVida2 = new javax.swing.JTextField();
        txtEstamina2 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnAtaque1 = new javax.swing.JButton();
        btnDefenza1 = new javax.swing.JButton();
        btnAtaqueFinal1 = new javax.swing.JButton();
        btnCurar1 = new javax.swing.JButton();
        btnAtaque2 = new javax.swing.JButton();
        btnAtaqueFinal2 = new javax.swing.JButton();
        btnDefenza2 = new javax.swing.JButton();
        btnCurar2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblLuchador1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblLuchador2 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblTituloPersonajes = new javax.swing.JLabel();
        cmbJugador1 = new javax.swing.JComboBox<>();
        cmbJugador2 = new javax.swing.JComboBox<>();
        btnRegistrarJugador = new javax.swing.JButton();
        cmbPersonajes = new javax.swing.JComboBox<>();
        lblPersonaje1 = new javax.swing.JLabel();
        btnEmpezar = new javax.swing.JButton();
        lblPersonaje3 = new javax.swing.JLabel();
        btnSelectJugador1 = new javax.swing.JButton();
        bntSelectJugador2 = new javax.swing.JButton();
        lblPersonaje2 = new javax.swing.JLabel();
        lblFondo2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        cmbJugadores.setBackground(new java.awt.Color(102, 255, 255));
        cmbJugadores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbJugadores.setForeground(new java.awt.Color(255, 255, 255));
        cmbJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJugadoresActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cedula");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Usuario");

        txtNombre.setBackground(new java.awt.Color(0, 0, 0));
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNombre.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNombre.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        txtApellido.setBackground(new java.awt.Color(0, 0, 0));
        txtApellido.setForeground(new java.awt.Color(255, 255, 255));
        txtApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApellido.setCaretColor(new java.awt.Color(255, 255, 255));
        txtApellido.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        txtCedula.setBackground(new java.awt.Color(0, 0, 0));
        txtCedula.setForeground(new java.awt.Color(255, 255, 255));
        txtCedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCedula.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCedula.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        txtUsuario.setBackground(new java.awt.Color(0, 0, 0));
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setCaretColor(new java.awt.Color(255, 255, 255));
        txtUsuario.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        tblRegistros.setBackground(new java.awt.Color(0, 0, 0));
        tblRegistros.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tblRegistros.setForeground(new java.awt.Color(255, 255, 255));
        tblRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id:", "Nombre:", "Apellido:", "Cedula:", "Usuario:", "Victorias:"
            }
        ));
        tblRegistros.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblRegistros);
        if (tblRegistros.getColumnModel().getColumnCount() > 0) {
            tblRegistros.getColumnModel().getColumn(0).setHeaderValue("id:");
            tblRegistros.getColumnModel().getColumn(1).setHeaderValue("Nombre:");
            tblRegistros.getColumnModel().getColumn(2).setHeaderValue("Apellido:");
            tblRegistros.getColumnModel().getColumn(3).setHeaderValue("Cedula:");
            tblRegistros.getColumnModel().getColumn(4).setHeaderValue("Usuario:");
            tblRegistros.getColumnModel().getColumn(5).setHeaderValue("Victorias:");
        }

        btnSeleccionPersonaje.setText("Ir a la Selección de Personaje");
        btnSeleccionPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionPersonajeActionPerformed(evt);
            }
        });

        lblFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registro.jpg"))); // NOI18N
        lblFondo1.setMaximumSize(new java.awt.Dimension(5000, 5000));
        lblFondo1.setMinimumSize(new java.awt.Dimension(5000, 5000));

        javax.swing.GroupLayout RegistroJugadorLayout = new javax.swing.GroupLayout(RegistroJugador.getContentPane());
        RegistroJugador.getContentPane().setLayout(RegistroJugadorLayout);
        RegistroJugadorLayout.setHorizontalGroup(
            RegistroJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroJugadorLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(cmbJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(RegistroJugadorLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(RegistroJugadorLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(RegistroJugadorLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(RegistroJugadorLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(RegistroJugadorLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(RegistroJugadorLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(btnSeleccionPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(RegistroJugadorLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(RegistroJugadorLayout.createSequentialGroup()
                .addGap(463, 463, 463)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(RegistroJugadorLayout.createSequentialGroup()
                .addGap(463, 463, 463)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(RegistroJugadorLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblFondo1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        RegistroJugadorLayout.setVerticalGroup(
            RegistroJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroJugadorLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(cmbJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(RegistroJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroJugadorLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4))
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(RegistroJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RegistroJugadorLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jLabel6)
                .addGap(14, 14, 14)
                .addGroup(RegistroJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroJugadorLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel7))
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnSeleccionPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(RegistroJugadorLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(RegistroJugadorLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(RegistroJugadorLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(RegistroJugadorLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel5))
            .addGroup(RegistroJugadorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblFondo1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelFondo.setBackground(new java.awt.Color(153, 255, 153));
        panelFondo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelFondo.setMaximumSize(new java.awt.Dimension(100, 100));
        panelFondo.setPreferredSize(new java.awt.Dimension(600, 600));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNombreJugador1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreJugador1.setText("jLabel1");

        jLabel1.setText("Vida:");

        jLabel2.setText("Estamina:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombreJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVida1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(txtEstamina1))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombreJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtEstamina1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNombreJugador2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreJugador2.setText("jLabel3");

        jLabel3.setText("Vida:");

        jLabel8.setText("Estamina: ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombreJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVida2)
                            .addComponent(txtEstamina2))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblNombreJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3))
                    .addComponent(txtVida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEstamina2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAtaque1.setText("Ataque");
        btnAtaque1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtaque1ActionPerformed(evt);
            }
        });

        btnDefenza1.setText("Defenza");

        btnAtaqueFinal1.setText("Ataque Final");

        btnCurar1.setText("Curar");
        btnCurar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurar1ActionPerformed(evt);
            }
        });

        btnAtaque2.setText("Ataque");
        btnAtaque2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtaque2ActionPerformed(evt);
            }
        });

        btnAtaqueFinal2.setText("Ataque Final");

        btnDefenza2.setText("Defenza");

        btnCurar2.setText("Curar");

        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(82, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAtaque1)
                            .addComponent(btnDefenza1))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAtaqueFinal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCurar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAtaque2)
                            .addComponent(btnDefenza2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAtaqueFinal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCurar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(68, 68, 68))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtaque1)
                    .addComponent(btnAtaqueFinal1)
                    .addComponent(btnAtaque2)
                    .addComponent(btnAtaqueFinal2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDefenza1)
                    .addComponent(btnCurar1)
                    .addComponent(btnDefenza2)
                    .addComponent(btnCurar2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/vs.jpg"))); // NOI18N
        jLabel11.setMinimumSize(new java.awt.Dimension(468, 468));
        jLabel11.setName(""); // NOI18N

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblLuchador1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLuchador2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(333, 333, 333)
                .addComponent(jLabel11, 0, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(442, 442, 442))
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLuchador1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(lblLuchador2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.getAccessibleContext().setAccessibleParent(jPanel6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );

        panelFondo.getAccessibleContext().setAccessibleParent(panelFondo);

        javax.swing.GroupLayout PantallaBatallaLayout = new javax.swing.GroupLayout(PantallaBatalla.getContentPane());
        PantallaBatalla.getContentPane().setLayout(PantallaBatallaLayout);
        PantallaBatallaLayout.setHorizontalGroup(
            PantallaBatallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaBatallaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        PantallaBatallaLayout.setVerticalGroup(
            PantallaBatallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaBatallaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(204, 0, 0));
        lblTitulo.setText("battle pro");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(330, 30, 161, 44);

        lblTituloPersonajes.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        lblTituloPersonajes.setForeground(new java.awt.Color(204, 0, 0));
        lblTituloPersonajes.setText("PERSONAJES");
        getContentPane().add(lblTituloPersonajes);
        lblTituloPersonajes.setBounds(325, 110, 110, 21);

        cmbJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJugador1ActionPerformed(evt);
            }
        });
        getContentPane().add(cmbJugador1);
        cmbJugador1.setBounds(42, 77, 120, 30);

        cmbJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJugador2ActionPerformed(evt);
            }
        });
        getContentPane().add(cmbJugador2);
        cmbJugador2.setBounds(561, 77, 135, 30);

        btnRegistrarJugador.setText("REGISTRAR JUGADOR");
        btnRegistrarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarJugadorActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarJugador);
        btnRegistrarJugador.setBounds(300, 430, 170, 30);

        cmbPersonajes.setFont(new java.awt.Font("Felix Titling", 0, 12)); // NOI18N
        cmbPersonajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPersonajesActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPersonajes);
        cmbPersonajes.setBounds(305, 140, 150, 30);
        getContentPane().add(lblPersonaje1);
        lblPersonaje1.setBounds(40, 130, 130, 130);

        btnEmpezar.setText("Empezar");
        btnEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpezarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmpezar);
        btnEmpezar.setBounds(340, 380, 90, 30);
        getContentPane().add(lblPersonaje3);
        lblPersonaje3.setBounds(305, 178, 146, 124);

        btnSelectJugador1.setText("Seleccionar Jugador 1 ");
        btnSelectJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectJugador1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectJugador1);
        btnSelectJugador1.setBounds(30, 291, 180, 30);

        bntSelectJugador2.setText("Seleccionar Jugador 2");
        bntSelectJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSelectJugador2ActionPerformed(evt);
            }
        });
        getContentPane().add(bntSelectJugador2);
        bntSelectJugador2.setBounds(547, 290, 180, 30);
        getContentPane().add(lblPersonaje2);
        lblPersonaje2.setBounds(570, 140, 120, 130);

        lblFondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondomain.jpg"))); // NOI18N
        lblFondo2.setMaximumSize(new java.awt.Dimension(800, 600));
        lblFondo2.setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().add(lblFondo2);
        lblFondo2.setBounds(0, -70, 810, 660);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 20, 750, 470);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clic.gif"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(90, 214, 460, 150);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarJugadorActionPerformed
        // TODO add your handling code here:
        RegistroJugador.setVisible(true);//Sea visible la ventana de registro
        RegistroJugador.setSize(600,600);//Dimension de la ventana              
    }//GEN-LAST:event_btnRegistrarJugadorActionPerformed

    private void btnSelectJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectJugador1ActionPerformed
        activarjugador2=true;
         //activarjugador1=true;
        int opcion = cmbPersonajes.getSelectedIndex();
        //Jugadores jugador1=new Jugadores();
         
        
        ImageIcon agua = new ImageIcon  (getClass().getResource("/Imagenes/agua2.gif"));
        ImageIcon fuego = new ImageIcon  (getClass().getResource("/Imagenes/fuego2.gif"));
        ImageIcon tierra = new ImageIcon  (getClass().getResource("/Imagenes/tierra2.gif"));
        ImageIcon aire = new ImageIcon  (getClass().getResource("/Imagenes/aire2.gif"));
        
        
        ImageIcon icono1 = new ImageIcon (agua.getImage().getScaledInstance(lblPersonaje1.getWidth(), lblPersonaje1.getHeight(), Image.SCALE_DEFAULT));
        ImageIcon icono2 = new ImageIcon (fuego.getImage().getScaledInstance(lblPersonaje1.getWidth(), lblPersonaje1.getHeight(), Image.SCALE_DEFAULT));
        ImageIcon icono3 = new ImageIcon (tierra.getImage().getScaledInstance(lblPersonaje1.getWidth(), lblPersonaje1.getHeight(), Image.SCALE_DEFAULT));
        ImageIcon icono4 = new ImageIcon (aire.getImage().getScaledInstance(lblPersonaje1.getWidth(), lblPersonaje1.getHeight(), Image.SCALE_DEFAULT));
//        ImageIcon icono5 = new ImageIcon (tierra2.getImage().getScaledInstance(lblLuchador1.getHeight(), lblLuchador1.getWidth(), Image.SCALE_DEFAULT));

        switch(opcion){
            case 0:
                lblPersonaje1.setIcon(icono1);
                lblLuchador1.setIcon(icono1);
                vida1 = 1200;
                txtVida1.setText(Integer.toString(vida1)+"/1200");
                estamina1 = 600;
                txtEstamina1.setText(Integer.toString(estamina1)+"/600");
                Jugadores personajeagua = new Jugadores (1200,600,100,210);
  
                break;
            case 1:
                lblPersonaje1.setIcon(icono2);
                lblLuchador1.setIcon(icono2);
                vida1 = 1300;
                txtVida1.setText(Integer.toString(vida1)+"/1300");
                estamina1 = 500;
                txtEstamina1.setText(Integer.toString(estamina1)+"/500");
               Jugadores personajefuego = new Jugadores (1300,500,110,230);
                break;
            case 2:
                lblPersonaje1.setIcon(icono3);
                lblLuchador1.setIcon(icono3);
                vida1 = 1400;
                txtVida1.setText(Integer.toString(vida1)+"/1400");
                estamina1 = 700;
                txtEstamina1.setText(Integer.toString(estamina1)+"/700");
                Jugadores personajetierra = new Jugadores (1400,700,95,156);
                break;
            case 3:
                lblPersonaje1.setIcon(icono4);
                lblLuchador1.setIcon(icono4);
                vida1 = 950;
                txtVida1.setText(Integer.toString(vida1)+"/950");
                estamina1 = 400;
                txtEstamina1.setText(Integer.toString(estamina1)+"/400");
                Jugadores personajeaire = new Jugadores (950,400,140,200);
                break;
            default:
                
                break;
        }
        
         if (activarjugador1 && activarjugador2){
            btnEmpezar.setEnabled(true);             
         }
    }//GEN-LAST:event_btnSelectJugador1ActionPerformed

    private void cmbJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJugador1ActionPerformed
        // TODO add your handling code here:  
        
       String NombreJugador1=cmbJugador1.getSelectedItem().toString();
       lblNombreJugador1.setText(NombreJugador1);
    }//GEN-LAST:event_cmbJugador1ActionPerformed

    private void cmbJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJugadoresActionPerformed
        // TODO add your handling code here:
        ClsJugador jugadorSeleccionado = (ClsJugador)cmbJugadores.getSelectedItem();

        txtNombre.setText(jugadorSeleccionado.getNombre());
        txtApellido.setText(jugadorSeleccionado.getApellido());
        txtUsuario.setText(jugadorSeleccionado.getUsuario());
        txtCedula.setText(jugadorSeleccionado.getCedula());
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnGuardar.setEnabled(false);

    }//GEN-LAST:event_cmbJugadoresActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String nombre=txtNombre.getText();
        String apellido=txtApellido.getText();
        String usuario=txtUsuario.getText();
        String cedula=txtCedula.getText();
        cont++;
        boolean jugadorExiste=false;
        
        ClsJugador jugadorP=new ClsJugador(cont, nombre, apellido,cedula, usuario,victorias);
        for(Object jugadorObj: jugador){
            
            ClsJugador m=(ClsJugador)jugadorObj;
            if(m.getCedula().equals(jugadorP.getCedula())){
                jugadorExiste=true;
                
                JOptionPane.showMessageDialog(rootPane, "Jugador con la misma cedula");
                break;
            }
            
            
            
        }
        
        if( !jugadorExiste &&!nombre.equals("") && !apellido.equals("") && !usuario.equals("")&&!cedula.equals("") ){

            jugador.add(jugadorP);
            controller.escribirObjeto("jugadores.dat", jugador);
            jugador=controller.extraerObjetos("jugadores.dat");

            limpiar();
            llenarCombo();

            Object jugadoresG [] = {jugadorP.getId(),jugadorP.getNombre(),jugadorP.getApellido(),jugadorP.getCedula(),jugadorP.getUsuario()};
            DefaultTableModel model = (DefaultTableModel) tblRegistros.getModel();
            model.addRow(jugadoresG);

        }
        
        else {
            JOptionPane.showMessageDialog(rootPane, "Llene todos los campos");
        }
        
        
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        ClsJugador jugadorSelect = (ClsJugador)cmbJugadores.getSelectedItem();
        DefaultTableModel model = (DefaultTableModel) tblRegistros.getModel();
        //System.out.println(cmbestudiantes.getSelectedIndex());
        //elimina el estudiante de la tabla cn remove row y select index x q elimina el indece d la tabla
        model.removeRow(cmbJugadores.getSelectedIndex());
        jugador.remove(jugadorSelect);
        controller.escribirObjeto("jugadores.dat", jugador);
        llenarCombo();
        limpiar();
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        ClsJugador jugadorSeleccionado = (ClsJugador)cmbJugadores.getSelectedItem();

        jugadorSeleccionado.setNombre(txtNombre.getText());
        jugadorSeleccionado.setCedula(txtCedula.getText());
        jugadorSeleccionado.setApellido(txtApellido.getText());
        jugadorSeleccionado.setUsuario(txtUsuario.getText());

        int id=jugadorSeleccionado.getId();
        String nombre=jugadorSeleccionado.getNombre();
        String apellido=jugadorSeleccionado.getApellido();
        String cedula=jugadorSeleccionado.getCedula();
        String usuario=jugadorSeleccionado.getUsuario();

        Object jugadoresG [] = {id,nombre,apellido,cedula,usuario};
        DefaultTableModel model = (DefaultTableModel) tblRegistros.getModel();
        model.removeRow(cmbJugadores.getSelectedIndex());
        jugador.remove(cmbJugadores.getSelectedIndex());
        model.insertRow(cmbJugadores.getSelectedIndex(), jugadoresG);
        jugador.add(cmbJugadores.getSelectedIndex(), jugadorSeleccionado);
        controller.escribirObjeto("jugadores.dat", jugador);
        llenarCombo();
        limpiar();
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnSeleccionPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionPersonajeActionPerformed
        // TODO add your handling code here:
        RegistroJugador.setVisible(false);//Cierra la ventana de registro
        RegistroJugador.setSize(700, 500);
        RegistroJugador.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSeleccionPersonajeActionPerformed

    private void bntSelectJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSelectJugador2ActionPerformed
        int opcion = cmbPersonajes.getSelectedIndex();
        activarjugador1=true;
        
        
        ImageIcon agua = new ImageIcon  (getClass().getResource("/Imagenes/agua2.gif"));
        ImageIcon fuego = new ImageIcon  (getClass().getResource("/Imagenes/fuego2.gif"));
        ImageIcon tierra = new ImageIcon  (getClass().getResource("/Imagenes/tierra2.gif"));
        ImageIcon aire = new ImageIcon  (getClass().getResource("/Imagenes/aire2.gif"));
        
        
        ImageIcon icono1 = new ImageIcon (agua.getImage().getScaledInstance(lblPersonaje2.getWidth(), lblPersonaje2.getHeight(), Image.SCALE_DEFAULT));
        ImageIcon icono2 = new ImageIcon (fuego.getImage().getScaledInstance(lblPersonaje2.getWidth(), lblPersonaje2.getHeight(), Image.SCALE_DEFAULT));
        ImageIcon icono3 = new ImageIcon (tierra.getImage().getScaledInstance(lblPersonaje2.getWidth(), lblPersonaje2.getHeight(), Image.SCALE_DEFAULT));
        ImageIcon icono4 = new ImageIcon (aire.getImage().getScaledInstance(lblPersonaje2.getWidth(), lblPersonaje2.getHeight(), Image.SCALE_DEFAULT));
        
        switch(opcion){
            case 0:
                lblPersonaje2.setIcon(icono1);
                lblLuchador2.setIcon(icono1);
                vida2 = 1200;
                
                estamina2 = 600;
                txtEstamina2.setText(Integer.toString(estamina2)+"/600");
                Jugadores personajeagua = new Jugadores (1200,600,100,210);
                txtVida2.setText(Integer.toString(personajeagua.getVida())+"/1200");
                break;
            case 1:
                lblPersonaje2.setIcon(icono2);
                lblLuchador2.setIcon(icono2);
                vida2 = 1300;
                txtVida2.setText(Integer.toString(vida2)+"/1300");
                estamina2 = 500;
                txtEstamina2.setText(Integer.toString(estamina2)+"/500");
                Jugadores personajefuego = new Jugadores (1300,500,110,230);
                break;
            case 2:
                lblPersonaje2.setIcon(icono3);
                lblLuchador2.setIcon(icono3);
                vida2 = 1400;
                txtVida2.setText(Integer.toString(vida2)+"/1400");
                estamina2 = 700;
                txtEstamina2.setText(Integer.toString(estamina2)+"/700");
                Jugadores personajetierra = new Jugadores (1400,700,95,156);
                break;
            case 3:
                lblPersonaje2.setIcon(icono4);
                lblLuchador2.setIcon(icono4);
                vida2 = 950;
                txtVida2.setText(Integer.toString(vida2)+"/950");
                estamina2 = 400;
                txtEstamina2.setText(Integer.toString(estamina2)+"/400");
                Jugadores personajeaire = new Jugadores (950,400,140,200);
                break;
            default:
                
                break;
        }
         if (activarjugador1 && activarjugador2){
            btnEmpezar.setEnabled(true);             
         }
                                  
    }//GEN-LAST:event_bntSelectJugador2ActionPerformed

    private void cmbPersonajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPersonajesActionPerformed
        // TODO add your handling code here:
        int opcion = cmbPersonajes.getSelectedIndex();
        ImageIcon agua = new ImageIcon  (getClass().getResource("/Imagenes/agua2.jpg"));
        ImageIcon fuego = new ImageIcon  (getClass().getResource("/Imagenes/fuego1.png"));
        ImageIcon tierra = new ImageIcon  (getClass().getResource("/Imagenes/tierra.png"));
        ImageIcon aire = new ImageIcon  (getClass().getResource("/Imagenes/airee.jpg"));
        
        
        ImageIcon icono1 = new ImageIcon (agua.getImage().getScaledInstance(lblPersonaje3.getWidth(), lblPersonaje3.getHeight(), Image.SCALE_DEFAULT));
        ImageIcon icono2 = new ImageIcon (fuego.getImage().getScaledInstance(lblPersonaje3.getWidth(), lblPersonaje3.getHeight(), Image.SCALE_DEFAULT));
        ImageIcon icono3 = new ImageIcon (tierra.getImage().getScaledInstance(lblPersonaje3.getWidth(), lblPersonaje3.getHeight(), Image.SCALE_DEFAULT));
        ImageIcon icono4 = new ImageIcon (aire.getImage().getScaledInstance(lblPersonaje3.getWidth(), lblPersonaje3.getHeight(), Image.SCALE_DEFAULT));

        switch(opcion){
            case 0:
                lblPersonaje3.setIcon(icono1);
                
                break;
            case 1:
                
                lblPersonaje3.setIcon(icono2);
                break;
            case 2:
                lblPersonaje3.setIcon(icono3);
                break;
            case 3:
                lblPersonaje3.setIcon(icono4);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_cmbPersonajesActionPerformed

    private void btnEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpezarActionPerformed
        // TODO add your handling code here:
        String SelectJugador1=cmbJugador1.getSelectedItem().toString();
        
         String SelectJugador2=cmbJugador2.getSelectedItem().toString();       
           
              
        if(SelectJugador1.equals(SelectJugador2)){
           JOptionPane.showMessageDialog(rootPane, "Los jugadores son los mismo");
           
        }
        else if( !cmbJugador1.equals(null)&&!cmbJugador2.equals(null)){
            
           PantallaBatalla.setVisible(true);
           PantallaBatalla.setSize(800, 640);
           PantallaBatalla.setLocationRelativeTo(null);
            
        }
       
        
        
    }//GEN-LAST:event_btnEmpezarActionPerformed

    private void cmbJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJugador2ActionPerformed
        // TODO add your handling code here:
        
       String NombreJugador2=cmbJugador2.getSelectedItem().toString();
       lblNombreJugador2.setText(NombreJugador2);
    }//GEN-LAST:event_cmbJugador2ActionPerformed

    private void btnCurar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurar1ActionPerformed
        // TODO add your handling code here:
        //////////VIDAS//

                                  
        //Integer.parseInt(lblVida1);

    }//GEN-LAST:event_btnCurar1ActionPerformed

    private void btnAtaque1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtaque1ActionPerformed
        
        Agua personaje1 = new Agua (1200,600,100,210);
        if(lblLuchador1.equals(personaje1)){
            
        }
    }//GEN-LAST:event_btnAtaque1ActionPerformed

    private void btnAtaque2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtaque2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtaque2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionJugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame PantallaBatalla;
    private javax.swing.JFrame RegistroJugador;
    private javax.swing.JButton bntSelectJugador2;
    private javax.swing.JButton btnAtaque1;
    private javax.swing.JButton btnAtaque2;
    private javax.swing.JButton btnAtaqueFinal1;
    private javax.swing.JButton btnAtaqueFinal2;
    private javax.swing.JButton btnCurar1;
    private javax.swing.JButton btnCurar2;
    private javax.swing.JButton btnDefenza1;
    private javax.swing.JButton btnDefenza2;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEmpezar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrarJugador;
    private javax.swing.JButton btnSeleccionPersonaje;
    private javax.swing.JButton btnSelectJugador1;
    public static javax.swing.JComboBox<String> cmbJugador1;
    public static javax.swing.JComboBox<String> cmbJugador2;
    private javax.swing.JComboBox<String> cmbJugadores;
    private javax.swing.JComboBox<String> cmbPersonajes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondo1;
    private javax.swing.JLabel lblFondo2;
    private javax.swing.JLabel lblLuchador1;
    private javax.swing.JLabel lblLuchador2;
    private javax.swing.JLabel lblNombreJugador1;
    private javax.swing.JLabel lblNombreJugador2;
    private javax.swing.JLabel lblPersonaje1;
    private javax.swing.JLabel lblPersonaje2;
    private javax.swing.JLabel lblPersonaje3;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloPersonajes;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JTable tblRegistros;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtEstamina1;
    private javax.swing.JTextField txtEstamina2;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtVida1;
    private javax.swing.JTextField txtVida2;
    // End of variables declaration//GEN-END:variables
}
